//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacionASPMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RENTCAREntities : DbContext
    {
        public RENTCAREntities()
            : base("name=RENTCAREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_LISTADOCLIENTES_Result> SP_LISTADOCLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTADOCLIENTES_Result>("SP_LISTADOCLIENTES");
        }
    }
}
